name: CI Manual

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you running the workflow?"
        required: false
        type: string
      environment:
        description: "Target environment"
        required: false
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  noop:
    name: No-op job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print context and inputs
        run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Input reason: ${{ inputs.reason }}"
          echo "Input environment: ${{ inputs.environment }}"
